### ISSUE TITLE
3.0.2 fails to decrypt /data

### ISSUE THREAD

**Issue by kerlerm** [TeamWin/android_device_samsung_maguro#1] opened 2016-10-13 19:27 UTC
I installed  TWRP-3.0.2 with CM-12.1-latest-nightly - all was fine.

Since I flashed cm-13.0-latest-nighly I can not decrypt /data here on maguro (Samsung Galaxy Nexus) TWRP 3.0.2 did work with an encrypted data partition on cm-12.1 but is unable to mount the encrypted cm-13.0 data partition. 

Same with TWRP-2.8 series
Same with  cm-13.0-20161013-NIGHTLY-maguro-recovery.img

Did something change in Android 6 regarding disk encryption?

There are already several issues with other devices on the main issue tracker.

TWRP Log attached:
[log_short.txt](https://github.com/TeamWin/android_device_samsung_maguro/files/528019/log_short.txt)

I can provide further information if needed. Please contact me.

**Comment by samesamebut** [comment] 2016-10-19 07:08
Can confirm!
Same with me. Decryption inside the Rom (CM-13) works (on boot).
While we in TWRP-3.0.2-0 it asks for password but always **fails** to decrypt

**Comment by kerlerm** [comment] 2016-10-20 18:54
There seems to be an unofficial build with hardware decryption:
http://forum.xda-developers.com/showpost.php?p=67975081&postcount=2014 (dated 31st July 2016 while official TWRP 3.0.2-0 is dated 5th April 2016)

**Comment by kerlerm** [comment] 2016-10-20 19:43
Official TWRP-3.0.2-0 was released without hardware decryption, because of some problems. So the unofficial build is the only recovery to get /data decrypted. 

Or we use `adb sideload /path/to/image`.

**Comment by samesamebut** [comment] 2016-10-27 09:29
The unoffical twrp is quite buggy (random reboots) and also has trouble to decrypt data if you have a different (hopefully long) key for decryption and another (probably shorter one) to unlock your device.

I use the adb sideload feature to run updates on the ROM (it work's because it doesn't write to the data partition but only to the unencrypted system partition)

There isn't any chance to run a backup (with the option to restore it) on the encrypted data partition... right?

**Comment by samesamebut** [comment] 2016-10-27 09:33
Confirmed on Android 7.1 as well!
Decryption inside the Rom (aosp_7.1_tuna_2016-10-21.zip) works (on boot).
While we in TWRP-3.0.2-0 it asks for password but fails to decrypt like on CM13 (Android 6.0.1)

**Comment by kerlerm** [comment] 2017-02-10 21:51
I lost hope that this TWRP bug will ever get fixed :( Did you switch to UnlegacyAndroid as a daily driver? Can you recommend it?

BTW: Do you know if there will ever be a maguro build from LineageOS?

**Comment by kerlerm** [comment] 2017-03-14 20:16
TWRP 3.1 still fails to decrypt data on maguro.

**Comment by Octav14n** [comment] 2017-04-24 14:38
I have also installed **TWRP 3.1**, the decryption does **not work** for me too. (Encrypted using LineageOS V13.0 -- Android 6.0.1 Marshmallow)

I installed the latest daily from LineageOS.
It is surprisingly fast and stable (if you reboot once a day), wlan/2g/3g are somewhat unstable but usable if you only chat/surf/watch videos, I have not tested the camera.
However activating the encryption slows down the system to be bareably usefull. The PlayStore for instance needs more than 5 secends to "respond" after being started.

**Comment by ravens** [comment] 2017-07-24 07:02
Still happening with TWRP 3.1.1 / encryption done with the nightly from July 2017 from LineageOS for maguro. TWRP fails to decrypt and keep asking for password.

**Comment by Manouchehri** [comment] 2017-08-08 23:44
I can confirm the TWRP build (`twrp-3.0.2-0-maguro-decrypt-test.img`) @kerlerm linked to works with `lineage-13.0-20170805-nightly-maguro-signed.zip`.

http://forum.xda-developers.com/showpost.php?p=67975081&postcount=2014

**Comment by andi34** [comment] 2017-08-16 12:59
Just reworked/updated our omni6 trees for maguro, toro, toroplus and common used tuna tree.

I also picked up where we stuck previously on decryption support, new TWRP.img for testing can be found here:
https://forum.xda-developers.com/showpost.php?p=73421863&postcount=2160

Source changes for hw decryption are on omniroms gerrit (changes mentioned in the xda post).

**Comment by andi34** [comment] 2017-08-24 15:41
Support for TWRP decryption merged in OmniRoms 7.x trees now.

**Comment by nailyk-fr** [comment] 2017-08-24 15:51
@andi34 should I still try to contact the twrp dev team then? 
Also AFAIK @bigbiff is mostly in charge of this.

**Comment by bigbiff** [comment] 2017-08-24 15:55
It is up to the maintainer (if any) of the device to fix it. I don't have a maguro.

**Comment by andi34** [comment] 2017-08-24 16:00
@bigbiff Ziyan ist the maintainer but he's busy in real life ATM. We finished what he started and I brought up the Omni7 trees (on official Omni GitHub)

@nailyk-fr no need if bigbiff can take a look at it.

**Comment by andi34** [comment] 2017-12-01 18:37
Solved on 3.2.0-0

**Comment by bigbiff** [comment] 2017-12-01 18:44
Thanks for the report.

**Closed as completed by bigbiff** 2017-12-01 18:44 UTC

**Comment by Manouchehri** [comment] 2017-12-01 20:14
Awesome, thanks!
